DIR   = /$(LIB)/rcscripts/sh
FILES = functions.sh init-common-post.sh init-common-pre.sh init-functions.sh \
	rc-daemon.sh rc-services.sh
EXES  = net.sh rc-help.sh

TOPDIR = ..
include $(TOPDIR)/default.mk
