#!/bin/bash
# Copyright (c) 2004-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Contributed by Roy Marples (uberlord@gentoo.org)

# char* adsl_provides(void)
#
# Returns a string to change module definition for starting up
adsl_provides() {
	echo "adsl"
}

# void adsl_depend(void)
#
# Sets up the dependancies for the module
adsl_depend() {
	after interface
	before dhcp
}

# bool adsl_check_installed(void)
#
# Returns 1 if rp-pppoe is installed, otherwise 0
adsl_check_installed() {
	[[ -x /usr/sbin/adsl-start ]] && return 0
	${1:-false} && eerror "For ADSL support, emerge net-dialup/rp-pppoe"
	return 1
}

# bool adsl_check_depends(void)
#
# Checks to see if we have the needed functions
adsl_check_depends() {
	return 0
}

# bool adsl_setup_vars(char *iface)
#
# Checks to see if the ADSL script has been created or not
adsl_setup_vars() {
	local iface="$1"

	# Decide which configuration to use.  Hopefully there is an
	# interface-specific one
	cfgfile="/etc/ppp/pppoe-${iface}.conf"
	[[ -f ${cfgfile} ]] || cfgfile="/etc/ppp/pppoe.conf"

	if [[ ! -f ${cfgfile} ]]; then
		eerror "no pppoe.conf file found!"
		eerror "Please run adsl-setup to create one"
		return 1
	fi

	return 0
}

# bool adsl_start(char *iface)
#
# Start ADSL on an interface by calling adsl-start
#
# Returns 0 (true) when successful, non-zero otherwise
adsl_start() {
	local iface="$1" user ifvar=$( bash_variable "$1" ) cfgfile

	adsl_setup_vars "${iface}" || return 1

	# Might or might not be set in conf.d/net
	eval user=\"\$\{adsl_user_${ifvar}\}\"

	# Start ADSL with the cfgfile, but override ETH and PIDFILE
	einfo "Starting ADSL for ${iface}"
	/usr/sbin/adsl-start <(cat "${cfgfile}"; \
	echo "ETH=${iface}"; \
	echo "PIDFILE=/var/run/adsl-${iface}.pid"; \
	[[ -n ${user} ]] && echo "USER=${user}") \
	>/dev/null
	eend $?
}

# bool adsl_stop(char *iface)
#
# Stop ADSL on an interface by calling adsl-stop
# Returns 0 when there is no ADSL to stop or we stop ADSL successfully
# Otherwise 1
adsl_stop() {
	local iface="$1" cfgfile

	adsl_check_installed || return 0
	[[ ! -f "/var/run/adsl-${iface}.pid" ]] && return 0

	adsl_setup_vars "${iface}" || return 0

	einfo "Stopping ADSL for ${iface}"
	/usr/sbin/adsl-stop <(cat "${cfgfile}"; \
	echo "ETH=${iface}"; echo "PIDFILE=/var/run/adsl-${iface}.pid") \
	>/dev/null
	eend $?
}

# vim:ts=4
