#!/bin/bash
# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-projects/bsd/fbsd/freebsd-rcscripts/etc/rc,v 1.1 2004/10/28 21:53:24 spb Exp $

# BSD's init works somewhat differently to sysvinit. This block should 'translate' from 
# the way init calls it to the way it would be called by sysvinit on linux.
if [ "$PPID" -eq "1" ]; then
	# We were called by init, going into multi-user mode.
	# Start services for sysinit, then boot, then default.
	# Exit with failure if any of them die.
	RUNLEVEL="1" bash /sbin/rc sysinit && \
		RUNLEVEL="1" bash /sbin/rc boot && \
		bash /sbin/rc default && \
		exit 0 || exit 1
fi

