DIR   = /$(LIB)/rcscripts/net 
FILES = adsl.sh apipa.sh arping.sh bonding.sh br2684ctl.sh bridge.sh clip.sh \
	ccwgroup.sh dhcpcd.sh ifconfig.sh ifplugd.sh ip6to4.sh \
	ipppd.sh iproute2.sh iptunnel.sh iwconfig.sh macchanger.sh \
	netplugd.sh pppd.sh pump.sh rename.sh tuntap.sh udhcpc.sh vlan.sh

TOPDIR = ..
include $(TOPDIR)/default.mk
