#!/bin/sh
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

# Contributed by Roy Marples (uberlord@gentoo.org)

exec /lib/rcscripts/net.modules.d/helpers.d/dhclient-udhcpc-wrapper ifconfig
