#!/bin/sh
# dhclient iproute2 module for net-scripts
# Version 1.0.4
# Copyright (c) 2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License V2
# Contributed by Roy Marples (uberlord@gentoo.org)

/lib/rcscripts/net.modules.d/helpers.d/dhclient-udhcpc-wrapper iproute2
exit $?
