#!/bin/bash
# Copyright (c) 2004-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

# Contributed by Roy Marples (uberlord@gentoo.org)

. /lib/rcscripts/sh/rc-services.sh

iface=${1##*/dhcpcd-}
iface=${iface%%.info}

if [[ $2 == "up" || $2 == "new" ]]; then
    mark_service_started net.${iface}
else
    mark_service_inactive net.${iface}
fi
