#!/bin/bash
# Copyright (c) 2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Contributed by Roy Marples (uberlord@gentoo.org)

interface="${1##*/dhcpcd-}"
interface="${interface%%.info}"

service="net.${interface}"

if [[ $2 != "up" && $2 != "new" ]]; then
    action="down"
else
    action="up"
fi

. /lib/rcscripts/net.modules.d/helpers.d/dhcp-state
