#!/bin/bash
# Copyright (c) 2005-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# Contributed by Roy Marples (uberlord@gentoo.org)

[[ $1 == "renewal" ]] && exit 0

action="$1"
interface="$2"

[[ ${RC_GOT_FUNCTIONS} != "yes" ]] && source /sbin/functions.sh
RC_QUIET_STDOUT="yes"

if [[ ${action} == "up" ]] ; then
	source "${svclib}/net.modules.d/helpers.d/module-loader"

	# Map MAC address variables to interface variables
	macnet_pre_start "${interface}"

	# Map wireless ESSID variables to interface variables
	if [[ -n ${wireless_module} ]] ; then
		if wireless_exists "${interface}" ; then
			essidnet_pre_start "${interface}"
		fi
	fi

	system_dns_extra "${interface}" "${statedir}/${interface}/resolv.conf" 
fi

source "${svclib}/net.modules.d/helpers.d/dhcp-state"

# vim: ts=4 :
