#!/bin/bash
# Copyright (c) 2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Contributed by Roy Marples (uberlord@gentoo.org)

[[ $1 == "renewal" ]] && exit 0

action="$1"
interface="$2"

if [[ ${action} == "up" ]]; then
	. /lib/rcscripts/net.modules.d/helpers.d/module-loader

	# Map MAC address variables to interface variables
	macnet_pre_start "${interface}" 1>/dev/null

	# Map wireless ESSID variables to interface variables
	if [[ -n ${wireless_module} ]]; then
		if wireless_exists "${interface}" ; then
			essidnet_pre_start "${interface}" 1>/dev/null
		fi
	fi

	system_dns_extra "${interface}" "${statedir}/${interface}/resolv.conf" 
fi

. /lib/rcscripts/net.modules.d/helpers.d/dhcp-state

# vim:ts=4
