#!/bin/bash
# udhcpc iproute2 module for net-scripts
# Version 0.6.3
# Copyright (c) 2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License V2
# Contributed by Roy "UberLord" Marples (uberlord@rsm.demon.co.uk)

/etc/net.modules.d/helpers.d/udhcpc-dhclient-wrapper iproute2 ${1}
exit $?
