#!/bin/sh
# udhcpc ifconfig module for net-scripts
# Version 1.0.3
# Copyright (c) 2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License V2
# Contributed by Roy Marples (uberlord@gentoo.org)

/lib/rcscripts/net.modules.d/helpers.d/udhcpc-dhclient-wrapper ifconfig ${1}
exit $?
