#!/bin/sh
# udhcpc ifconfig module for net-scripts
# Version 1.0.0
# Copyright (c) 2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License V2
# Contributed by Roy Marples (uberlord@gentoo.org)

action=${1}
echo ${action}

case "${action}" in
	bound|renew|deconfig)
		# We handle these actions
		;;
	nak|leasefail)
		# These are valid actions, but we don't handle them
		exit 0
		;;
	*)
		echo "We don't handle that action"
		exit 1
		;;
esac

[[ ${action} == nak ]] && exit 0

# Fix any potential localisation problems
# Note that LC_ALL trumps LC_anything_else according to locale(7)
ifconfig() {
	LC_ALL=C /sbin/ifconfig "$@"
}

# Remove all aliases
for i in $( ifconfig | grep -o "^${interface}:[0-9]*" | tac | xargs ); do
	ifconfig ${i} down
done

# Remove all addresses - iproute2 does not need to create dummy interfaces for
# aliased addresses
while ifconfig ${interface} | grep -q -m1 -o 'inet addr:[^ ]*' ; do
	ifconfig ${interface} 0
done
	
# Remove IPv6 addresses
for i in $( ifconfig ${interface} | awk '$1=="inet6" && $4!="Scope:Link" {print $3}' ); do
	ifconfig ${interface} inet6 del ${i} &>/dev/null
done

/sbin/ifconfig ${interface} up &>/dev/null

[[ ${action} == deconfig ]] && exit 0

if [[ ${action} == bound ]]; then
	ip=( ${ip} )
	subnet=( ${subnet} )
	broadcast=( ${broadcast} )
	for (( i=0; i<${#ip[@]}; i++ )); do
		[[ ${i} -eq 0 ]] && l=${interface} || l=${interface}:${i}

		b=${broadcast[i]}
		[[ -n ${b} ]] && b="broadcast ${b}"

		ifconfig ${l} inet ${ip[i]} netmask ${subnet[i]} ${b}
	done

	for r in ${router}; do
		/sbin/route add default gw ${r} dev ${interface}
	done
fi

# Set our module to udhcpc if it's not set
[[ -z ${module} ]] && module=udhcpc
source /lib/rcscripts/net.modules.d/helpers.d/config-system
config_system

exit 0
