#!/bin/sh
# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2

# BSD's init works somewhat differently to sysvinit.
# This block should 'translate' from the way init calls it to the way it would
# be called by sysvinit on linux.
if [ "$PPID" -eq "1" ]; then
	# We were called by init, going into multi-user mode.
	# Start services for sysinit, then boot, then default.
	# Exit with failure if any of them die.
	RUNLEVEL="1" /sbin/rc sysinit || exit 1
	RUNLEVEL="1" /sbin/rc boot || exit 1
	/sbin/rc default || exit 1
	exit 0
fi

