#!/bin/sh
#RCUPDATE:2 3 4:75:This line is required for script management

PIDFILE=/var/run/sshd.pid
EXE=/usr/sbin/sshd

gen_keys() {
	if [ ! -e /etc/ssh/ssh_host_key ] 
	then
		einfo "Generating Hostkey..."
  		/usr/bin/ssh-keygen -b 1024 -f /etc/ssh/ssh_host_key -N ''
	fi
	if [ ! -e /etc/ssh/ssh_host_dsa_key ]
	then
		einfo "Generating DSA-Hostkey..."
		/usr/bin/ssh-keygen -d -f /etc/ssh/ssh_host_dsa_key -N ''
	fi
}

start() {
   	gen_keys
	ebegin "Starting sshd"
	start-stop-daemon --start --quiet --exec $EXE
	eend $? 
}

stop() {
	ebegin "Stopping sshd"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $EXE
	eend $? 
}





